/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package regis_admin;
import Koneksi.koneksiDB;
import Menu.MenuSPP;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Oka
 */
public class formRegis extends javax.swing.JFrame {

    /**
     * Creates new form formRegis
     */
    public formRegis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtnamaL = new javax.swing.JTextField();
        txtnip = new javax.swing.JTextField();
        jpass = new javax.swing.JPasswordField();
        jconfirm = new javax.swing.JPasswordField();
        cbjenis = new javax.swing.JComboBox<>();
        btnregis = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        txtuser = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Registrasi Admin ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 10, 240, 58);

        jLabel2.setText("Nama Lengkap");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 80, 90, 20);

        jLabel3.setText("NIP");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 120, 80, 20);

        jLabel4.setText("Email");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 160, 70, 20);

        jLabel5.setText("Username");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 210, 70, 20);

        jLabel6.setText("Password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 250, 70, 20);

        jLabel7.setText("Confirmasi Password");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 290, 100, 20);

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel1.add(txtemail);
        txtemail.setBounds(150, 160, 320, 30);

        jLabel8.setText("Jenis Kelamin");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 330, 80, 20);

        txtnamaL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaLActionPerformed(evt);
            }
        });
        jPanel1.add(txtnamaL);
        txtnamaL.setBounds(150, 80, 320, 30);

        txtnip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnipActionPerformed(evt);
            }
        });
        jPanel1.add(txtnip);
        txtnip.setBounds(150, 120, 320, 30);
        jPanel1.add(jpass);
        jpass.setBounds(150, 240, 320, 30);
        jPanel1.add(jconfirm);
        jconfirm.setBounds(150, 280, 320, 30);

        cbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Item", "Perempuan ", "Laki-laki" }));
        cbjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjenisActionPerformed(evt);
            }
        });
        jPanel1.add(cbjenis);
        cbjenis.setBounds(150, 320, 320, 30);

        btnregis.setText("Regis");
        btnregis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregisActionPerformed(evt);
            }
        });
        jPanel1.add(btnregis);
        btnregis.setBounds(160, 380, 70, 23);

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback);
        btnback.setBounds(410, 380, 55, 23);

        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        jPanel1.add(txtuser);
        txtuser.setBounds(150, 200, 320, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtnamaLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaLActionPerformed

    private void txtnipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnipActionPerformed

    private void cbjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbjenisActionPerformed

    private void btnregisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregisActionPerformed
        // TODO add your handling code here:
        try{
            String sql ="INSERT INTO registrasi_admin VALUES('"+txtnamaL.getText()+"','"+txtnip.getText()+"','"+txtemail.getText()+"','"+txtuser.getText()+"','"+jpass.getText()+"','"+jconfirm.getText()+"','"+cbjenis.getSelectedItem()+"')";
            java.sql.Connection conn = (Connection)koneksiDB.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Registrasi Berhasil");
        }catch(HeadlessException | SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnregisActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
         new MenuSPP().setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formRegis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formRegis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formRegis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formRegis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formRegis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnregis;
    private javax.swing.JComboBox<String> cbjenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jconfirm;
    private javax.swing.JPasswordField jpass;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnamaL;
    private javax.swing.JTextField txtnip;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
    
