/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Data;
import Formlogin.Login;
import Koneksi.koneksiDB;
import Menu.MenuSPP;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import jxl.Workbook;
import jxl.write.Label;
import jxl.write.WritableCell;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
/**
 *
 * @author Oka
 */
public class DataTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form DataTransaksi
     */
    private void initTabel()
    {
        try{
           Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_login","root","");
           Statement statement = koneksi.createStatement();
           ResultSet res = statement.executeQuery("SELECT *, datamhs.nama as namamhs, datastaf.nama as namapeg FROM datatransaksi JOIN datamhs ON datatransaksi.`data_mhs_id` = datamhs.`id_data_mhs`\n" +
"JOIN master_ukt ON master_ukt.`id_master_ukt` = datamhs.`id_data_mhs` JOIN datastaff ON datastaff.`id_pegawai` = datatransaksi.`data_pegawai_id` WHERE datamhs.`nim`  = '"+txtCari.getText()+"';");
           DefaultTableModel tbl = new DefaultTableModel();
           tbl.addColumn("NIM");
           tbl.addColumn("Nama");
           tbl.addColumn("Tanggal");
           tbl.addColumn("Nama_UKT");
           tbl.addColumn("Biaya");
           tbl.addColumn("Semester");
           tbl.addColumn("Jurusan");
           tbl.addColumn("Nama Pegawai");
           tbl.addColumn("TahunAjar");
           tbl.addColumn("Status");
           
           tabel.setModel(tbl);
           while(res.next()){
               tbl.addRow(new Object []{
                   res.getString("nim"),
                   res.getString("nama"),
                   res.getString("tanggal"),
                   res.getString("nama_ukt"),
                   res.getString("biaya"),
                   res.getString("semester"),
                   res.getString("jurusan"),
                   res.getString("namapegawai"),
                   res.getString("tahunajar"),
                   res.getString("status"),
               });
               tabel.setModel(tbl);
               
               txtnama.setText(res.getString("nama"));
               txtCari.setText(res.getString("nim"));
               txtjurusan.setText(res.getString("jurusan"));
           }
           Statement statement2 = koneksi.createStatement();
           ResultSet res2 = statement2.executeQuery("SELECT sum(master_ukt.`biaya`) as harga FROM datatransaksi JOIN datamhs ON datatransaksi.`data_mhs_id` = datamhs.`id_data_mhs`\n" +
           "JOIN master_ukt ON master_ukt.`id_master_ukt` = datamhs.`id_data_mhs` JOIN datastaff ON datastaff.`id_pegawai` = datatransaksi.`data_pegawai_id` WHERE datamhs.`nim`  = '"+txtCari.getText()+"' AND STATUS='BELUM LUNAS';");
           res2.next();
                totalBayar.setText(res2.getString("harga").toString());
       } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage().toString());
        }
    }
    
    public DataTransaksi() {
        initComponents();
        int year = Calendar.getInstance().get(Calendar.YEAR);
        for(int i=year; i>=2000;i--)
        {
            String a = Integer.toString(i);
        }
        
        String tanggalan = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());
        labelTanggal.setText(tanggalan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtjurusan = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        totalBayar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        txtpenurunan = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnbaru = new javax.swing.JButton();
        btncetak = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtUangTunai = new javax.swing.JTextField();
        txtUangKembali = new javax.swing.JTextField();
        labelTanggal = new javax.swing.JLabel();
        namaPetugas = new javax.swing.JLabel();
        nipPetugas = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnbayar = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 20)); // NOI18N
        jLabel1.setText("Menu Transaksi Pembayaran SPP");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(320, 10, 370, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Menu ini Digunakan untuk Melakukan Transaksi Pembayaran");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 60, 370, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Pilih Siswa dan Detail Pembayaran");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 90, 240, 30);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setText("NIM ");

        jLabel5.setText("NAMA");

        jLabel6.setText("JURUSAN");

        btnCari.setText("CARI");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        totalBayar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBayarActionPerformed(evt);
            }
        });

        jLabel7.setText("PENURUNAN UKT");

        jCheckBox2.setText("TIDAK");

        jCheckBox1.setText("YA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtnama, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                .addComponent(txtjurusan))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCari)))
                        .addGap(18, 18, 18)
                        .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtpenurunan)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(txtpenurunan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 120, 570, 190);

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(0, 51, 102));

        btnbaru.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnbaru.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oka\\Documents\\label\\icons8-add-481.png")); // NOI18N
        btnbaru.setText("Baru");
        btnbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbaruActionPerformed(evt);
            }
        });

        btncetak.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btncetak.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oka\\Documents\\label\\icons8-bill-481.png")); // NOI18N
        btncetak.setText("Cetak Kwitansi");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncetak, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbaru, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnbaru, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncetak)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(610, 120, 230, 130);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabel);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 320, 870, 140);

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oka\\Documents\\label\\icons8-stack-of-money-100mm.png")); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(250, 20, 55, 50);

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Uang Tunai");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Uang Kembali");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Tanggal");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Petugas");

        txtUangTunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUangTunaiActionPerformed(evt);
            }
        });
        txtUangTunai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUangTunaiKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUangKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(txtUangTunai, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(nipPetugas, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                    .addComponent(labelTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaPetugas, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtUangTunai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namaPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nipPetugas, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUangKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnbayar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnbayar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oka\\Documents\\label\\icons8-ok-48,.png")); // NOI18N
        btnbayar.setText("Bayar");
        btnbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbayarActionPerformed(evt);
            }
        });

        btnbatal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnbatal.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oka\\Documents\\label\\icons8-cancel-48 (1)..png")); // NOI18N
        btnbatal.setText("Batal");
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oka\\Downloads\\icons8-exit-48j.png")); // NOI18N
        btnLogout.setText("Log-Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Oka\\Documents\\label\\icons8-back-to-48...png")); // NOI18N
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnbatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbayar)
                    .addComponent(btnbatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Data Pembayaran");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("PROSES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 917, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUangTunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUangTunaiActionPerformed
        
    }//GEN-LAST:event_txtUangTunaiActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
         try{
           Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_login","root","");
           Statement statement = koneksi.createStatement();
           ResultSet res = statement.executeQuery("SELECT B.`nim`, B.`nama`, A.`tanggal`,  D.`nama_ukt`, D.`biaya`, A.`semester`, B.`jurusan`, E.`nama` AS namapegawai, A.`tahunajar`, A.`status` FROM `datatransaksi` A INNER JOIN `datamhs` B ON B.`id_data_mhs` = A.`data_mhs_id` INNER JOIN  `ukt` C ON A.`id_ukt` = C.`id_ukt` INNER JOIN  `master_ukt` D ON C.`id_master_ukt` = D.`id_master_ukt` LEFT JOIN `datastaff` E ON A.`data_pegawai_id` = E.`id_pegawai` WHERE B.nim = '"+txtCari.getText()+"';");
           
           DefaultTableModel tbl = new DefaultTableModel();
           tbl.addColumn("NIM");
           tbl.addColumn("Nama");
           tbl.addColumn("Tanggal");
           tbl.addColumn("Nama_UKT");
           tbl.addColumn("Biaya");
           tbl.addColumn("Semester");
           tbl.addColumn("Jurusan");
           tbl.addColumn("Nama Pegawai");
           tbl.addColumn("TahunAjar");
           tbl.addColumn("Status");
           
           tabel.setModel(tbl);
           while(res.next()){
               tbl.addRow(new Object []{
                   res.getString("nim"),
                   res.getString("nama"),
                   res.getString("tanggal"),
                   res.getString("nama_ukt"),
                   res.getString("biaya"),
                   res.getString("semester"),
                   res.getString("jurusan"),
                   res.getString("namapegawai"),
                   res.getString("tahunajar"),
                   res.getString("status"),
               });
               tabel.setModel(tbl);
               
               txtnama.setText(res.getString("nama"));
               txtCari.setText(res.getString("nim"));
               txtjurusan.setText(res.getString("jurusan"));
           }
         
                  
           Connection koneksi2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_login","root","");
           Statement statement2 = koneksi2.createStatement();
             ResultSet res2 = statement2.executeQuery("SELECT  SUM(D.`biaya`) AS biaya\n"+
                "FROM `datatransaksi` A , `datamhs` B, `ukt` C, `master_ukt` D\n"+  
                "WHERE A.`data_mhs_id` = C.`data_mhs_id` AND A.`id_ukt` = C.`id_ukt` AND C.`id_master_ukt` = D.`id_master_ukt` AND A.`data_mhs_id` = B.`id_data_mhs` \n"+
                "AND A.`status` = 'BELUM LUNAS' AND B.nim = '"+txtCari.getText()+"';");
            //("SELECT sum(biaya) as biaya FROM datatransaksi JOIN datamhs ON datatransaksi.`data_mhs_id` = datamhs.`id_data_mhs`\n" +
            //"JOIN master_ukt ON master_ukt.`id_master_ukt` = datamhs.`id_data_mhs` JOIN datastaff ON datastaff.`id_pegawai` = datatransaksi.`data_pegawai_id` WHERE datamhs.`nim`  = '"+txtCari.getText()+"' AND STATUS='BELUM LUNAS';");
           res2.next();
           
             totalBayar.setText(res2.getString("biaya").toString());
           
       } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage().toString());
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:new Login().setVisible(true);
      new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbaruActionPerformed
        // TODO add your handling code here:
        txtCari.setText("");
        txtnama.setText("");
        txtjurusan.setText("");
        txtpenurunan.setText("");
        txtUangTunai.setText("");
        txtUangKembali.setText("");
        txtCari.requestFocus();
    }//GEN-LAST:event_btnbaruActionPerformed

    private void txtUangTunaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUangTunaiKeyPressed
        // TODO add your handling code here
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            double harga = Double.parseDouble(totalBayar.getText());
            double tunai = Double.parseDouble(txtUangTunai.getText());
            double kembalian = tunai - harga;
            txtUangKembali.setText(Double.toString(kembalian));
        }
    }//GEN-LAST:event_txtUangTunaiKeyPressed

    private void btnbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbayarActionPerformed
        // TODO add your handling code here:
        try{
            double harga = Double.parseDouble(totalBayar.getText());
            double tunai = Double.parseDouble(txtUangTunai.getText());
            double kembalian = tunai - harga;
           if(kembalian >= 0){
                 Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_login","root","");
                Statement statement = koneksi.createStatement();
                statement.execute("UPDATE datatransaksi JOIN datamhs ON datatransaksi.`data_mhs_id` = datamhs.`id_data_mhs` SET status = 'LUNAS', data_pegawai_id = '"+nipPetugas.getText()+"', tanggal='"+labelTanggal.getText()+"' WHERE nim = '" + txtCari.getText() + "' AND status = 'BELUM LUNAS';");
                JOptionPane.showMessageDialog(rootPane, "Pembayaran Berhasil");
                initTabel();
                totalBayar.setText(txtUangKembali.getText());
           }else {
               JOptionPane.showMessageDialog(rootPane, "Uang Anda Kurang");
           }
         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage().toString());
        }
    }//GEN-LAST:event_btnbayarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Menu.MenuSPP().setVisible(true); 
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void totalBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalBayarActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Pembayaran Dibatalkan");
        dispose();
    }//GEN-LAST:event_btnbatalActionPerformed

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
        // TODO add your handling code here:
        try {
            Workbook workbook = Workbook.getWorkbook(new File("F:\\Laporan\\data3.xls"));  
            WritableWorkbook copy = Workbook.createWorkbook(new File("F:\\Laporan\\Kwitansi_mahasiswa.xls"), workbook);
            WritableSheet sheet2 = copy.getSheet(0); 
            WritableCell cell = sheet2.getWritableCell(2, 2); 
                       
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_login","root","");
            Statement statement = koneksi.createStatement();
            ResultSet res = statement.executeQuery("SELECT B.`nim`, B.`nama`, D.`nama_ukt`, D.`biaya`, A.`semester`, B.`jurusan`, A.`tahunajar`, A.`status` \n" +
            "FROM `datatransaksi` A \n" +
            "INNER JOIN `datamhs` B ON B.`id_data_mhs` = A.`data_mhs_id` \n" +
            "INNER JOIN  `ukt` C ON A.`id_ukt` = C.`id_ukt` \n" +
            "INNER JOIN  `master_ukt` D ON C.`id_master_ukt` = D.`id_master_ukt`\n" +
            "WHERE B.nim = '"+txtCari.getText()+"';");
            
            res.next();
            String nim = res.getString("nim");
            Label label = new Label(2, 2, nim); 
            sheet2.addCell(label);
            
            String nama = res.getString("nama");
            label = new Label(2, 3, nama); 
            sheet2.addCell(label);
            
            String jurusan = res.getString("jurusan");
            label = new Label(2, 4, jurusan); 
            sheet2.addCell(label);
            
            int nomer = 1;
            label = new Label(1, 8, Integer.toString(nomer)); 
            sheet2.addCell(label);
            
            String tahunajar = res.getString("tahunajar");
            label = new Label(2, 8, tahunajar); 
            sheet2.addCell(label);
            
            String semester = res.getString("semester");
            label = new Label(3, 8, semester); 
            sheet2.addCell(label);
            
            String gol = res.getString("nama_ukt");
            label = new Label(4, 8, gol); 
            sheet2.addCell(label);
            
            String tagihan = res.getString("biaya");
            label = new Label(5, 8, tagihan); 
            sheet2.addCell(label);
            
            String status = res.getString("status");
            label = new Label(6, 8, status); 
            sheet2.addCell(label);
            
            int row,col;
            // di exel (0,0) = A,1
            //col = 0 ; // berarti mulai dari kolom A
            row = 9 ; // berarti mulai dari baris 5
            
            while(res.next())
            {  
                nomer++;
                label = new Label(1, row, Integer.toString(nomer)); 
                sheet2.addCell(label);

                tahunajar = res.getString("tahunajar");
                label = new Label(2, row, tahunajar); 
                sheet2.addCell(label);

                semester = res.getString("semester");
                label = new Label(3, row, semester); 
                sheet2.addCell(label);

                gol = res.getString("nama_ukt");
                label = new Label(4, row, gol); 
                sheet2.addCell(label);

                tagihan = res.getString("biaya");
                label = new Label(5, row, tagihan); 
                sheet2.addCell(label);

                status = res.getString("status");
                label = new Label(6, row, status); 
                sheet2.addCell(label);
                row++;
            }
            
            row = row + 2;
            status = "Tertanda";
            label = new Label(5, row, status); 
            sheet2.addCell(label);
            row++;
            status = "Bagian Keuangan";
            label = new Label(5, row, status); 
            sheet2.addCell(label);
            row=row+3;
            status = "Admin Bagian Keuangan";
            label = new Label(5, row, status); 
            sheet2.addCell(label);

            statement.close();
            koneksi.close();
            copy.write(); 
            copy.close();
            workbook.close();
            JOptionPane.showMessageDialog(rootPane, "Laporan Berhasil");
            
            //tampilkan laporan
            try
            {
                Desktop.getDesktop().open(new File("F:\\Laporan\\Kwitansi_mahasiswa.xls"));
                //String fileName = "F:\\Laporan\\Laporan_mahasiswa.xls";
                //String[] commands = {"cmd", "/d", "start", "\"DummyTitle\"",fileName};
                //Runtime.getRuntime().exec(commands);
            } catch(IOException ie){
                JOptionPane.showMessageDialog(rootPane, "Terjadi Kesalahanmembuka excel"+ie);
            } 
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Terjadi Kesalahan! di :"+e);
        }
    }//GEN-LAST:event_btncetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnbaru;
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnbayar;
    private javax.swing.JButton btncetak;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelTanggal;
    public javax.swing.JLabel namaPetugas;
    public javax.swing.JLabel nipPetugas;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField totalBayar;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtUangKembali;
    private javax.swing.JTextField txtUangTunai;
    private javax.swing.JTextField txtjurusan;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtpenurunan;
    // End of variables declaration//GEN-END:variables
}

