/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Data;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oka
 */
public class SetUKT extends javax.swing.JFrame {

    /**
     * Creates new form SetUKT
     */
    public SetUKT() {
        initComponents();
        isicomboUKT();
        label_id_master_ukt.setVisible(false);
    }
    
    private void isicomboUKT()
    {
        try{
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_login","root","");
            Statement statement = koneksi.createStatement();
            ResultSet res = statement.executeQuery("SELECT * FROM master_ukt;");
            //String id_ukt = res.getString("id_master_ukt");
            comboUKT.removeAllItems();
            while(res.next()){
                comboUKT.addItem(res.getString("nama_ukt"));
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage().toString());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCari = new javax.swing.JButton();
        cariNim = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtNominal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnsetUKT = new javax.swing.JButton();
        comboUKT = new javax.swing.JComboBox<>();
        label_id_master_ukt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        btnCari.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCari.setText("CARI");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("FORM SET UKT");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("NIM");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("NAMA");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("GANTI UKT");

        txtNominal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNominalActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("KEMBALI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnsetUKT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnsetUKT.setText("PINDAHKAN");
        btnsetUKT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsetUKTActionPerformed(evt);
            }
        });

        comboUKT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboUKT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboUKTItemStateChanged(evt);
            }
        });
        comboUKT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboUKTActionPerformed(evt);
            }
        });

        label_id_master_ukt.setText("jLabel5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cariNim, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNama))
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_id_master_ukt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboUKT, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNominal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsetUKT)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariNim, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsetUKT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboUKT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_id_master_ukt)
                    .addComponent(txtNominal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        try{
           Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_login","root","");
           Statement statement = koneksi.createStatement();
           ResultSet res = statement.executeQuery("SELECT D.nim, D.`nama`\n" +
            "FROM `datamhs` D\n" +
            "WHERE D.nim = '"+cariNim.getText()+"';");
           
           while(res.next()){
               cariNim.setText(res.getString("nim"));
               txtNama.setText(res.getString("nama"));
           }
           
           
           Statement statement2 = koneksi.createStatement();
           ResultSet res2 = statement2.executeQuery("SELECT A.`tanggal`, B.`nama_ukt`, B.`biaya`, A.`status`\n" +
            "FROM `ukt` A, `master_ukt` B, `datamhs` C\n" +
            "WHERE A.`id_master_ukt` = B.`id_master_ukt` AND A.`data_mhs_id` = C.`id_data_mhs` AND C.`nim` = '"+cariNim.getText()+"';");
           
           DefaultTableModel tbl = new DefaultTableModel();
           tbl.addColumn("Tanggal");
           tbl.addColumn("UKT");
           tbl.addColumn("Biaya");
           tbl.addColumn("Status");
           
           tabel.setModel(tbl);
           while(res2.next()){
               tbl.addRow(new Object []{
                   res2.getDate("tanggal"),
                   res2.getString("nama_ukt"),
                   res2.getString("biaya"),
                   res2.getString("status"),
               });
               tabel.setModel(tbl);
           }
       } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage().toString());
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void insertBaru(String x)
    {
        try{
           Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_login","root","");
           Statement statement = koneksi.createStatement();
           statement.execute("UPDATE ukt SET status = 'Non Aktif' WHERE data_mhs_id='"+x+"';");
           statement.execute("INSERT INTO ukt(data_mhs_id,status,id_master_ukt,tanggal) VALUE('"+x+"','Aktif','"+label_id_master_ukt.getText()+"',DATE_FORMAT(NOW(),'%Y-%m-%d'))");
           JOptionPane.showMessageDialog(rootPane,"Update Berhasil");
           habisSave();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage().toString());
        }
    }
    
    private void habisSave()
    {
        try{
           Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_login","root","");
           Statement statement = koneksi.createStatement();
           ResultSet res = statement.executeQuery("SELECT D.nim, D.`nama`\n" +
            "FROM `datamhs` D\n" +
            "WHERE D.nim = '"+cariNim.getText()+"';");
           
           while(res.next()){
               cariNim.setText(res.getString("nim"));
               txtNama.setText(res.getString("nama"));
           }
           
           
           Statement statement2 = koneksi.createStatement();
           ResultSet res2 = statement2.executeQuery("SELECT A.`tanggal`, B.`nama_ukt`, B.`biaya`, A.`status`\n" +
            "FROM `ukt` A, `master_ukt` B, `datamhs` C\n" +
            "WHERE A.`id_master_ukt` = B.`id_master_ukt` AND A.`data_mhs_id` = C.`id_data_mhs` AND C.`nim` = '"+cariNim.getText()+"';");
           
           DefaultTableModel tbl = new DefaultTableModel();
           tbl.addColumn("Tanggal");
           tbl.addColumn("UKT");
           tbl.addColumn("Biaya");
           tbl.addColumn("Status");
           
           tabel.setModel(tbl);
           while(res2.next()){
               tbl.addRow(new Object []{
                   res2.getDate("tanggal"),
                   res2.getString("nama_ukt"),
                   res2.getString("biaya"),
                   res2.getString("status"),
               });
               tabel.setModel(tbl);
           }
       } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage().toString());
        }
    }
    
  
    
    private void btnsetUKTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsetUKTActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Yakin Memindahkan UKT Mahasiswa ini?", "WARNING",
        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try{
                Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_login","root","");
                Statement statement = koneksi.createStatement();
                ResultSet res = statement.executeQuery("SELECT A.`id_data_mhs`\n" +
                "FROM `datamhs` A WHERE A.`nim` = '"+cariNim.getText()+"'");
                String ininim = "";
                while(res.next())
                {
                    ininim = res.getString("id_data_mhs");
                    
                }
                insertBaru(ininim);
                
            }catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage().toString());
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Aksi dibatalkan!");
        }
        
        
        
        
        
    }//GEN-LAST:event_btnsetUKTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Menu.MenuSPP().setVisible(true); 
        this.dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboUKTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboUKTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboUKTActionPerformed

    private void comboUKTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboUKTItemStateChanged
        // TODO add your handling code here:
        Object item = evt.getItem();

        if (evt.getStateChange() == evt.SELECTED) {
            try{
                Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_login","root","");
                Statement statement = koneksi.createStatement();
                ResultSet res = statement.executeQuery("SELECT A.* FROM `master_ukt` A WHERE A.nama_ukt = '"+item+"';");
               
                while(res.next()){
                    label_id_master_ukt.setText(res.getString("id_master_ukt"));
                    txtNominal.setText(res.getString("biaya"));
                }
                
            }catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage().toString());
            }
        } 
    }//GEN-LAST:event_comboUKTItemStateChanged

    private void txtNominalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNominalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNominalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetUKT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetUKT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetUKT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetUKT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetUKT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnsetUKT;
    private javax.swing.JTextField cariNim;
    private javax.swing.JComboBox<String> comboUKT;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_id_master_ukt;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNominal;
    // End of variables declaration//GEN-END:variables

}
